-- =============================================================================
-- 個人モード用問題バンク作成
-- TEAM_A_DB.DEVELOPMENT.DAY5_QUIZ_INDIVIDUAL_QUESTIONS
-- =============================================================================

CREATE OR REPLACE TABLE TEAM_A_DB.DEVELOPMENT.DAY5_QUIZ_INDIVIDUAL_QUESTIONS AS
WITH user_cats AS (
  SELECT
    USER_ID_HASH,
    ANSWER_AGE_BAND,
    ANSWER_GENDER,
    ANSWER_MARRIAGE,
    CATEGORY_PATH,
    ROW_NUMBER() OVER (
      PARTITION BY USER_ID_HASH
      ORDER BY HASH(USER_ID_HASH, CATEGORY_PATH, 2026)
    ) AS CAT_RN
  FROM TEAM_A_DB.DEVELOPMENT.DAY5_QUIZ_INDIVIDUAL_CANDIDATES
),
top5_per_user AS (
  SELECT
    USER_ID_HASH,
    ANSWER_AGE_BAND,
    ANSWER_GENDER,
    ANSWER_MARRIAGE,
    ARRAY_AGG(OBJECT_CONSTRUCT(
      'rank', CAT_RN,
      'categoryPath', CATEGORY_PATH
    )) WITHIN GROUP (ORDER BY CAT_RN) AS CATEGORIES,
    LISTAGG(CATEGORY_PATH, ' / ') WITHIN GROUP (ORDER BY CATEGORY_PATH) AS CAT_SIG
  FROM user_cats
  WHERE CAT_RN <= 5
  GROUP BY USER_ID_HASH, ANSWER_AGE_BAND, ANSWER_GENDER, ANSWER_MARRIAGE
),
unique_signatures AS (
  -- 同じカテゴリ5件で正解属性が分かれるものを除外
  SELECT CAT_SIG
  FROM top5_per_user
  GROUP BY CAT_SIG
  HAVING COUNT(DISTINCT ANSWER_AGE_BAND || '-' || ANSWER_GENDER || '-' || ANSWER_MARRIAGE) = 1
),
ranked_candidates AS (
  SELECT
    t.*,
    ROW_NUMBER() OVER (
      PARTITION BY t.ANSWER_AGE_BAND, t.ANSWER_GENDER, t.ANSWER_MARRIAGE
      ORDER BY HASH(t.USER_ID_HASH, 42)
    ) AS SEGMENT_Q_NUM
  FROM top5_per_user t
  INNER JOIN unique_signatures u ON t.CAT_SIG = u.CAT_SIG
)
SELECT
  UUID_STRING() AS QUESTION_ID,
  ANSWER_AGE_BAND,
  ANSWER_GENDER,
  ANSWER_MARRIAGE,
  CATEGORIES,
  'individual_random5' AS RANKING_METHOD,
  '2023-04-01'::DATE AS PERIOD_START,
  '2024-03-31'::DATE AS PERIOD_END,
  'v1' AS DATA_VERSION,
  TRUE AS IS_ACTIVE,
  CURRENT_TIMESTAMP() AS CREATED_AT
FROM ranked_candidates
WHERE SEGMENT_Q_NUM <= 5;

